# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    leyes_boe: {}

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Servicio de versionado de assets
    App\Service\AssetVersionService: ~
    App\Service\AssetVersionStrategy:
        arguments:
            $versionService: '@App\Service\AssetVersionService'
    
    # Servicio de partidas multijugador
    App\Service\PartidaPreguntasService:
        arguments:
            $cache: '@cache.partidas'
    
    # Servicio de BOE con caché (usa cache.app)
    App\Service\BoeLeyService:
        arguments:
            $cache: '@cache.app'
    
    # Repositorios con cache para consultas comunes
    App\Repository\LeyRepository:
        arguments:
            $cache: '@cache.queries'
    
    App\Repository\TemaRepository:
        arguments:
            $cache: '@cache.queries'
    
    App\Repository\ConvocatoriaRepository:
        arguments:
            $cache: '@cache.queries'
    
    App\Repository\ExamenRepository:
        arguments:
            $cache: '@cache.queries'
    
    App\Repository\MunicipioRepository:
        arguments:
            $cache: '@cache.queries'
    
    App\Repository\TemaMunicipalRepository:
        arguments:
            $cache: '@cache.queries'
    
    # Event listener para invalidar cache automáticamente
    App\EventListener\CacheInvalidationSubscriber:
        arguments:
            $leyRepository: '@App\Repository\LeyRepository'
            $temaRepository: '@App\Repository\TemaRepository'
            $convocatoriaRepository: '@App\Repository\ConvocatoriaRepository'
            $municipioRepository: '@App\Repository\MunicipioRepository'
            $temaMunicipalRepository: '@App\Repository\TemaMunicipalRepository'
            $examenRepository: '@App\Repository\ExamenRepository'
            $cache: '@cache.queries'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }